DATA:
    ROOT: ''
    TRAIN_FILE: 'data/ssv2/train.csv'
    VAL_FILE: 'data/ssv2/val.csv'
    DATASET: ssv2
    NUM_FRAMES: 8
    NUM_CLASSES: 174
    LABEL_LIST: 'labels/ssv2_174_labels.csv'
    BATCH_SIZE: 32
MODEL:
  TYPE: vit_base
  NAME: vit_base
  DROP_PATH_RATE: 0.5
  NUM_CLASSES: 174
  PRETRAINED: True
TRAIN:
  BASE_LR: 0.1
  WARMUP_LR: 0.001
  MIN_LR: 0.001
  EPOCHS: 30
  WEIGHT_DECAY: 1e-4
  OPTIMIZER:
    NAME: "sgd"
  WARMUP_EPOCHS: 20
  #PRETRAINED_PATH: '/focalnet_base_srf.pth'
  PRETRAINED_PATH: ''
AUG:
  FRAME_INTERVAL: 4
  FLIP_RATIO: 0.0
  COLOR_JITTER: 0.8
  GRAY_SCALE: 0.2
  MIXUP: 0.8
  MIXUP_PROB: 0.5
SAVE_FREQ: 1
